<meta charset="utf-8">
<?php View::content() ?>

<?php echo View::partial("menu"); ?>
<section class="entidad-encabezado">
    <?php echo Html::img($entidad->logo,$entidad->logo) ?>
    <h1><?php echo $entidad->nombre; ?></h1>
    <p><?php echo $entidad->descripcion; ?></p>
    <h4>Admin: Steffany Terán /  <?php echo Html::link("cliente/logout","Salir") ?></h4>
</section> 

<section class="listado-sesiones">
	<fieldset class="sesiones-editar" style="padding:10px;margin:5px;width:50%;float:left;margin-right:40px;">
		<legend>Editar Sesión</legend>
		<?php echo Form::openMultipart() ?>
			<label>Nombre</label><br>
			<?php echo Form::text("sesiones.nombre","readonly class='form-control'",$sesiones->nombre) ?><br>
			<label>Ubicación</label><br>
			<?php echo Form::hidden("sesiones.id",null,$sesiones->id) ?>

			<?php echo Form::textarea("sesiones.ubicacion","class='form-control' rows='2'",$sesiones->ubicacion) ?><br>
			<label>Descripción</label><br>
			<?php echo Form::textarea("sesiones.descripcion","class='form-control' rows='4'",$sesiones->descripcion) ?><br>
			<!--<label>Imagen de Sesión</label><br>
			<?php //echo Form::file("archivo") ?><br><br>-->
			<?php echo Form::hidden("sesiones.imagen",null,'') ?>
			<?php echo Form::submit("Editar","class='btn btn-default btn-sm' style='float:right;'") ?>
		</form>
	</fieldset>
		<fieldset class="sesiones-archivos" style="padding:10px;margin:5px;width:45%;margin-top:80px;">
			<legend>Subir Archivos</legend>
				<?php echo Form::openMultipart() ?>
				<label>Subir Documentos</label><br>
				<input type="file" multiple="multiple" name="documentos[]">
				<?php echo Form::hidden("documentos_ocultos",null,"asd") ?><br><br>
				<?php echo Form::submit("Agregar","class='btn btn-default btn-sm' style='float:right;'") ?>
			<?php echo Form::close() ?>
		</fieldset>
		<?php if ($documentos): ?>
			<fieldset style="padding:10px;margin:5px;width:300px">
			<legend>Documentos</legend>
			<ul>
				<?php foreach ($documentos as $key => $value): ?>
					<li><?php echo Html::link($value->adjunto,$value->nombre) ?></li>
				<?php endforeach ?>
			</ul>
			</fieldset>
		<?php endif ?>

</section>