    <section class="entidad">
      <section class="entidad-linea"></section>
        <section class="entidad-menu">
          <div class="menus">
              <ul>
                <li><?php echo Html::link("administracion","Administración") ?></li>
                 <li><?php echo Html::link("cliente/logout","Salir del Sistema") ?></li> 
               </ul>
          </div>
        </section>
      </section>
