<?php echo Tag::css("jquery-ui/jquery-ui.min") ?>
<?php echo Tag::js("jquery-ui/jquery-ui.min") ?>
<?php echo Tag::css("datatable/css/jquery.dataTables.min") ?>
<script type="text/javascript">
	$(document).ready(function(){
		 $.datepicker.regional['es'] = {
		 closeText: 'Cerrar',
		 prevText: '<Ant',
		 nextText: 'Sig>',
		 currentText: 'Hoy',
		 monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
		 monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
		 dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
		 dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
		 dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
		 weekHeader: 'Sm',
		 dateFormat: 'dd/mm/yy',
		 firstDay: 1,
		 isRTL: false,
		 showMonthAfterYear: false,
		 yearSuffix: ''
		 };
 	$.datepicker.setDefaults($.datepicker.regional['es']);
		$(".datepicker").datepicker({
			changeMonth: true,
      		changeYear: true
		});
	})
</script>
<?php if (Auth::is_valid() and Auth::get("role") == 'participante'): ?>
	<?php $deshabilitar = "display:none;" ?>
	<?php $disabled = "disable readonly" ?>
<?php else: ?>
	<?php $deshabilitar = "" ?>
	<?php $disabled = "" ?>

<?php endif ?>

<?php if (Auth::is_valid()): ?>
    <?php if (Auth::get("role") == "admin"): ?>
		<?php echo View::partial("menu_entidad"); ?>
	<?php else: ?>
		<?php echo View::partial("menu"); ?>
	<?php endif ?>
<?php endif ?>

<section class="entidad-encabezado">
    <?php echo Html::img($entidad->logo,$entidad->logo) ?>
    <h1><?php echo $entidad->nombre; ?></h1>
    <p><?php echo $entidad->descripcion; ?></p>

    <?php if (Auth::is_valid() and Auth::get("role") == 'participante'): ?>
    <h4>Participante: <?php echo Auth::get("participante");?> /  <?php echo Html::link("cliente/logout","Salir") ?></h4>
	<?php else: ?>
    <h4>Admin: <?php echo Auth::get("nombre")." ".Auth::get("apellido"); ?> /  <?php echo Html::link("cliente/logout","Salir") ?></h4>
	<?php endif ?>
</section> 

<section class="listado-sesiones">

<div id="inicio">
<?php if (isset($sesiones_creadas) and $sesiones_creadas): ?>
	<p>Seleccione el año</p>

	<div class="sesion-lista">
		<table class="table table-striped">
	  		<thead>
	  			<th>AÑO</th>
	  			<th>SESIONES</th>
	  			<th></th>
	  		</thead>
	  		<tbody>
	  			<?php foreach ($sesiones_creadas as $key => $value): ?>
					<tr>
						<td align="center"><?php echo $key ?></td>
						<td align="center"><?php echo count($value) ?></td>
						<td><button class="btn btn-default btn-xs"><i class="glyphicon glyphicon-search"></i><?php echo Html::link("{$entidad->nombre}/sesiones/".md5($entidad->nombre)."/".$key," Ver listado") ?></button></td>
					</tr>
				<?php endforeach ?>
	  		
	  		</tbody>
		</table>
	</div>
	<?php 
	$sesion=$entidad->id;
	$ultima=Load::model("sesiones")->find("sesiones.entidad_id=$sesion ORDER BY id DESC LIMIT 1 ");
	 ?>
	 <?php foreach ($ultima as $ultimas): ?>
		<div class="entidad-titulo-reciente">
			<p>ÚLTIMA SESIÓN INGRESADA</p>
		</div>
		<div class="entidad-sesion-reciente">
			<p><b><?php echo $ultimas->nombre; ?> </b></p>
			<p><?php echo $ultimas->descripcion; ?></p>
			<p><small><?php echo implode( '-', array_reverse( explode( '-', $ultimas->fecha_sesion ) ) )?></small></p>
		</div>
	<?php endforeach ?>
<?php endif ?>
</div>


<fieldset id="config-general" class="sesiones-editar" style="margin:left;padding:10px;margin-bottom:5px;display:none;">
	<fieldset style="width:50%;float:left;">
	<legend>Configuración general:</legend>
	<?php View::content() ?>
	<?php echo Form::openMultipart() ?>
		<label>Ubicación</label><br>
		<input type="text" name="entidad[ubicacion]" <?php echo $disabled ?> class='form-control  input-sm' style="width:100%" value="<?php echo $entidad->ubicacion ?>"><br>
		<label>Descripción</label><br>
		<textarea name="entidad[descripcion]" style="width:100%"  <?php echo $disabled ?>  class='form-control  input-sm' cols="30" rows="4"><?php echo $entidad->descripcion ?></textarea><br>
		<div style="<?php echo $deshabilitar?>">
		<label>Logo</label><br>
		<?php //echo Html::img($entidad->logo,$entidad->logo,"style='width:200px'") ?><br>
		<input type="file" name="logo"  <?php echo $disabled ?>  value=""><br><br>
		</div>
		<input type="hidden" name="entidad[id]"  <?php echo $disabled ?>  value="<?php echo $entidad->id ?>">
		<?php echo Form::submit("Modificar","class='btn btn-default btn-sm' style='float:right;$deshabilitar'") ?>
	</form>
	</fieldset>

		
	<fieldset style="width:45%;margin:auto;padding:10px;margin-bottom:5px;margin-top:72px;float:right;">
	<fieldset>
	<legend>Datos del Cliente</legend>
	<?php echo Form::open() ?>
	 <div class="form-group">
		<label style='float:left;margin-bottom:5px;margin-right:10px;'>Nombre y Apellido</label>
		<?php echo Form::text("cliente.nombre","class='form-control  input-sm' $disabled style='width:130px;float:left;margin-right:5px;'") ?>
		<?php echo Form::text("cliente.apellido","class='form-control  input-sm' $disabled style='width:130px;float:left;'") ?>
	</div>
		<label>Nombre Del Participante:</label>
		<?php echo Form::text("cliente.participante","class='form-control  input-sm' readonly disabled") ?>
		<label style="margin-top:10px;">Código acceso (PARTICIPANTE)</label><br>
		<?php echo Form::text("cliente.cod_acceso","class='form-control  input-sm' $disabled") ?><br>
		<label>Teléfono</label><br>
		<?php echo Form::text("cliente.tlf","class='form-control  input-sm' $disabled") ?><br>
		
		<br>
		<?php echo Form::submit("Modificar","class='btn btn-default btn-sm'  style='float:right;$deshabilitar'") ?>
	<?php echo Form::close() ?>
	</fieldset>

		<div style="background:#eee;padding:50px;margin-top:20px;<?php echo $deshabilitar ?>">
			<?php echo Form::open() ?>
		<!--<fieldset style="width:45%;margin:auto;padding:10px;margin-bottom:5px">-->
			<legend>Cambio de Clave</legend>
			 <div class="form-group">
				<label for="" style="float:left;width:120px;margin-top:5px;">Clave Anterior</label>
				<input type="password" name="clave" class='form-control  input-sm' style="width:183px;"><br>
				<label for="" style="float:left;width:120px;margin-top:5px;">Clave Nueva</label>
				<input type="password" name="clave_nueva" class='form-control  input-sm' style="width:183px;">
			</div>
			<input type="submit" value="Cambiar Clave" class='btn btn-default btn-sm' name="cambio_clave" style="float:right;margin-bottom:20px;">

		<?php echo Form::close() ?>
		</div>	
	</fieldset>
</fieldset>
<!--<fieldset style="width:50%;margin:auto;padding:10px;margin-bottom:5px">
	<legend>Crear Nueva Sesion</legend>
	<?php //echo Form::openMultipart() ?>
	<label>Fecha de Sesion</label><br>
	<input type="text" required name="sesiones[fecha_sesion]" class="datepicker"><br>
	<label>Nombre</label><br>
	<input type="text" required name="sesiones[nombre]"><br>
	<label>Ubicacion</label><br>
	<input type="text" name="sesiones[ubicacion]"><br>
	<label>Descripcion</label><br>
	<input type="text" name="sesiones[descripcion]"><br>
	<label>Imagen</label><br>
	<input type="file" name="sesion_imagen"><br><br>
	<label>Archivos</label><br> -->
	<!-- <input type="file" name="sesion_archivos[]" multiple="multiple"><br><br> 
	<input type="submit" value="Crear Sesion" name="nueva_sesion">
	<?php //echo Form::close() ?>
</fieldset>-->

<?php if (isset($sesiones_creadas) and $sesiones_creadas): ?>
	<fieldset  style="width:400px;margin:auto;padding:5px;display:none;">
	<legend>Sesiones por Año</legend>
		<table class="datatable">
			<thead>
				<th>Año</th>
				<th>Número de Sesiones</th>
				<th>Ver</th>
			</thead>

			<?php foreach ($sesiones_creadas as $key => $value): ?>
				<tr>
					<td align="center"><?php echo $key ?></td>
					<td align="center"><?php echo count($value) ?></td>
					<td><?php echo Html::link("{$entidad->nombre}/sesiones/".md5($entidad->nombre)."/".$key,"Ver sesiones") ?></td>
				</tr>
			<?php endforeach ?>
		</table>
	</fieldset>
<?php endif ?>
</section>