<?php View::content(); ?>
<meta charset="utf-8">
<style type="text/css">
th{
	font-family: 'Century Gothic';
}
td{
	font-size: 14px;
}
#playlist, #player {
width: 400px; /* Ancho de todo el contenedor */
padding: 20px;
margin: 0 auto;
display: block;
text-align: center;
font-family: Verdana;
}
#player {
/* Imagen de fondo del primer contenedor */
padding: 10px 20px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
width: 960px;
}
audio {
width:300px; /* Ancho del reproductor */
margin:0 auto;
display: inline-block
}
#player:after {
/* Imagen animada */
content: url(//lh3.googleusercontent.com/-KoD5KVOAsGQ/U1B_dWFttoI/AAAAAAAAFFc/uJ3SjLPlDHQ/s75/equalizador.gif);
padding-left: 10px;
}
#playlist {
margin: 0 auto 20px auto;
display: block;
background: #424242; /* Fondo del segundo contenedor */
border-top: 5px solid #9F111B;
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
text-align: left;
font-size: 12px; /* Estilos de fuente */
font-family: 'Trebuchet MS', Trebuchet, Verdana, sans-serif;
font-weight: normal;
}
#playlist li, #playlist ul li {
background-image: none;
list-style-type: none;
padding: 0;
margin: 0;
}
#playlist li a {
color: #CCC; /* Color de las canciones */
background: #222; /* Fondo de las canciones */
padding: 7px 5px;
display: block;
padding-left: 10px;
text-decoration: none;
}
#playlist li a:hover{
/*background: #9F111B; /* Color de fondo al pasar el cursor */
text-decoration: none;
background: rgb(10,100,100);
}
#playlist .active a {
color: #B11623; /* Color de la canción activa */
font-style: italic;
text-decoration: none;
}
#playlist .active a:before {
content: "\25B6";
color: #CCC;
font-style: normal;
padding-right: 8px;
}
#playlist .active a:hover {
color: #222; /* Color de la canción activa al pasar el cursor */
}

</style>
<?php echo Tag::js("jquery/jquery.min") ?>
<?php echo Tag::css("datatable/css/jquery.dataTables") ?>
<?php echo Tag::js("datatable/jquery.dataTables") ?>

<?php if (Auth::is_valid()): ?>
    <?php if (Auth::get("role") == "admin"): ?>
		<?php echo View::partial("menu_entidad"); ?>
	<?php else: ?>
		<?php echo View::partial("menu"); ?>
	<?php endif ?>
<?php endif ?>

<section class="entidad-encabezado" style="margin-bottom:50px;">
    <?php echo Html::img($entidad->logo,$entidad->logo) ?>
    <h1><?php echo $entidad->nombre; ?></h1>
    <p><?php echo $entidad->descripcion; ?></p>
    <?php if (Auth::is_valid()): ?>
    	
	    <?php if (Auth::get("role") == 'participante'): ?>
	    <h4>Participante: <?php echo Auth::get("participante");?> /  <?php echo Html::link("cliente/logout","Salir") ?></h4>
		<?php else: ?>
			<?php if (Auth::is_valid()): ?>
				
		    	<h4>Admin: <?php echo Auth::get("nombre")." ".Auth::get("apellido"); ?> /  <?php echo Html::link("cliente/logout","Salir") ?></h4>
			<?php endif ?>
		<?php endif ?>
    <?php endif ?>

</section> 

<section style="position:relative;margin:auto;width:960px;">
<?php if ($participaciones): ?>
<div id=''>
	<fieldset class="sesiones-editar" style="padding:10px;margin:5px;">
	<legend>SESIÓN COMPLETA</legend>

	<center>
	<audio controls='' onplay="primeraVez()" id='audio' preload='auto' tabindex='0' type='audio/mpeg'>
		<?php //foreach ($participaciones as $key => $value): ?>
			<source src="<?php echo PUBLIC_PATH."files/uploads/$entidad->nombre/{$participaciones[0]->verificarFechaSesion($sesion->fecha_sesion)}.$sesion->nombre/".str_replace(":", "-", $participaciones[0]->tiempo)."_".$participaciones[0]->nombre_participante.".mp3" ?>" tiempoparticipante="<?php echo str_replace(":", "-", $participaciones[0]->tiempo) ?>" nombreparticipante="<?php echo $participaciones[0]->nombre_participante ?>"  type='audio/mp3'/>
		<?php //endforeach ?>
		Hola, tu navegador no está actualizado y no puede mostrar este contenido.
	</audio>
	<div id="reproduciendo">
		
	</div>
	</center>
	<br>
</div>
<div class="" style="width:600px;margin:auto">
	<table class="datatable" style="font-family:Verdana;margin-top:20px;">
		<thead>
			<th>Participaciones</th>
			<?php if (Auth::is_valid()): ?>
				<?php if (Auth::get("role")=="participante"): ?>
					<th>Sin Acción</th>

				<?php else: ?>
					<th>Acción</th>
				<?php endif ?>
			<?php endif ?>
		</thead>

		<?php $activa = 0 ?>
		<?php foreach ($participaciones as $key => $value): ?>
		<tr>
	<?php if ($activa == 0): ?>
	<td class='active'>
		<a class="track"  href="<?php echo PUBLIC_PATH."files/uploads/$entidad->nombre/{$value->verificarFechaSesion($sesion->fecha_sesion)}.$sesion->nombre/".str_replace(":", "-", $value->tiempo)."_".$value->nombre_participante.".mp3" ?>" tiempoparticipante="<?php echo str_replace(":", "-", $value->tiempo) ?>" nombreparticipante="<?php echo $value->nombre_participante ?>"><?php echo $value->tiempo." ".$value->nombre_participante ?></a>
	</td>
		<?php if (Auth::is_valid()): ?>
			
			<?php if (Auth::get("role")=="participante"): ?>
				<td><center>--</center>	</td>
			<?php else: ?>
				<td>
					<b style="font-size:12px;">Activar/desactivar</b>
					<?php if ($value->status): ?>
					<input type="checkbox" checked id="<?php echo $value->id ?>" class="activar_participacion" title="Si esta Checked, esta Visible al participante">
				<?php else: ?>
					<input type="checkbox" id="<?php echo $value->id ?>" class="activar_participacion" title="Si esta Checked, esta Visible al participante">
				<?php endif ?>
				</td>
			<?php endif ?>
		<?php endif ?>
	<?php else: ?>
	<td>
			<a class="track"  tiempoparticipante="<?php echo str_replace(":", "-", $value->tiempo) ?>" nombreparticipante="<?php echo $value->nombre_participante ?>" href="<?php echo PUBLIC_PATH."files/uploads/$entidad->nombre/{$value->verificarFechaSesion($sesion->fecha_sesion)}.$sesion->nombre/".str_replace(":", "-", $value->tiempo)."_".$value->nombre_participante.".mp3" ?>"><?php echo $value->tiempo." ".$value->nombre_participante ?></a>
		</td>
		<?php if (Auth::is_valid()): ?>
			
			<?php if (Auth::get("role")=="participante"): ?>
				<td><center>--</center></td>
			<?php else: ?>
				<td>
						<b style="font-size:12px;">Activar/desactivar</b>
						<?php if ($value->status): ?>
						<input type="checkbox" checked id="<?php echo $value->id ?>" class="activar_participacion" title="Si esta Checked, esta Visible al participante">

					<?php else: ?>
						<input type="checkbox" id="<?php echo $value->id ?>" class="activar_participacion" title="Si esta Checked, esta Visible al participante">
				<?php endif ?>
				</td>
			<?php endif ?>
		<?php endif ?>
<?php endif ?>
<?php $activa++ ?>

</tr>
<?php endforeach ?>	

</table>
</div>
<?php else: ?>

	<h4 style="text-align:center;font-family:Verdana;">No hay Participaciones Agregadas</h4>

<?php endif ?>
</section>
<?php echo Tag::js("jquery/jquery.min") ?>

<script>
var primeravez=0;
var audio;
var playlist;
var tracks;
var current;
function primeraVez(){
	if (!primeravez) {
		primeravez=1;
		tiempo = $("audio source").attr('tiempoparticipante');
		nombre = $("audio source").attr('nombreparticipante');
		$("#reproduciendo").html("<b>Nombre: </b>"+nombre+" <br> <b>Tiempo: </b>"+tiempo);
	};
}
$(document).ready(function(){
	$("body").on("click",".activar_participacion",function(){
		$("body").off("click",".activar_participacion",function(){})
		var id = $(this).attr("id");
			$.ajax({
				dataType:"json",
				url:"../cambiarSesionStatus/"+id,
				success:function(r){

					if (r.respuesta==true) {
						alert("Estado de la sesion cambiado")
					}else{
						alert("Error")

					}
				}
			})
			$(".datatable").DataTable({
					"language":{
					    "sProcessing":     "Procesando...",
					    "sLengthMenu":     "Mostrar _MENU_ registros",
					    "sZeroRecords":    "No se encontraron resultados",
					    "sEmptyTable":     "Ningún dato disponible en esta tabla",
					    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
					    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
					    "sInfoPostFix":    "",
					    "sSearch":         "Buscar:",
					    "sUrl":            "",
					    "sInfoThousands":  ",",
					    "sLoadingRecords": "Cargando...",
					    "oPaginate": {
					        "sFirst":    "Primero",
					        "sLast":     "Último",
					        "sNext":     "Siguiente",
					        "sPrevious": "Anterior"
					    },
					    "oAria": {
					        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
					        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
					    }
					}
			});
			$("body").on("click",".datatable a",function(){
				$("body").off("click",".datatable a",function(){})
				//initaudio();
				/*$("audio source").attr("src",$(this).attr("href"))
				alert("asd")
				$("#reproduciendo").html($(this).attr("src").split("_")[1])
				var audio = $("audio")[0];

				audio.load();
				audio.play();
				initaudio()*/
				
				return false;
			})
			$("body").on("click",".track",function(){
				$("body").off("click",".track",function(){})
				tiempo = $(this).attr('tiempoparticipante');
				nombre = $(this).attr('nombreparticipante');
				console.log(tiempo,audio)
				
				return false;
			})
			$("body").on("change","search",function(){
				$("body").off("change","search",function(){})
				initaudio()
			})
		

		
	})

	initaudio();
})

function initaudio(){
	current=0;
	//alert("arrancando")
	audio=$('audio');
	tracks=$(".track");

	len=tracks.length-1;
	audio[0].volume=1;
	tracks.click(function(e){
		e.preventDefault();
		link=$(this);
		current=link.parent().index();
		runaudio(link,audio[0])
	});
	audio[0].addEventListener('ended',function(e){
		current++;
		if(current>len){
			current=0;
			link=tracks[0]
		}else{
			link=tracks[current]
		}
		runaudio($(link),audio[0])
	})
	
}
function runaudio(link,player){

	//console.log(link)
	$("audio source").attr('src',link.attr('href'));
	tiempo = link.attr('tiempoparticipante');
	nombre = link.attr('nombreparticipante');
	$("#reproduciendo").html("<b>Nombre: </b>"+nombre+" <br> <b>Tiempo: </b>"+tiempo);
	par=link.parent();
	//par.addClass('active').siblings().removeClass('active');
	audio[0].load();
	audio[0].play()
}


</script>

<?php if ($documentos): ?>
<section class="listado-sesiones">	
	<fieldset class="sesiones-editar" style="padding:10px;margin:5px;">
	<legend>Documentos</legend>
	<ul>
		<?php foreach ($documentos as $key => $value): ?>
			<li style="list-style:none;"><?php echo Html::link($value->adjunto,$value->nombre) ?></li>
		<?php endforeach ?>
	</ul>
	</fieldset>
</section>
<?php endif ?>
