<div class="capa-contenido" id="somos">
    <div class="fondo_titulo"><p>Nuestra Empresa - Profesionalidad y Eficiencia</p></div>
        <div id="quienes_somos">
            <div class="quienes-somos">
            <p>Somos profesionales con grandes conocimientos en las deficiencias y necesidades que encontramos en el mundo empresarial, destacando las administraciones públicas, sometidas a rigurosas leyes de obligado cumplimiento con un único fin, el poder llegar a todos los ciudadanos de la manera más eficiente, rápida, cómoda y transparente posible.</p>
            <?php echo Html::img("regmeet/empresa_edificio.jpg") ?>
            <div class="mensaje-quienes-somos">
                Regmeet te ofrece una herramienta de fácil uso, que te conecta con la comunidad <br> <a href="#servicios" onclick="servicios()">Regmeet App</a> 
            </div>
        </div>
    </div>
</div>

<div class="capa-contenido" id="service" style="display:none;">
    <div class="fondo_titulo"><p>Nuestros Servicios</p></div>
        <div id="servicios">
            <div class="servicios-empresa">
                <p><b style="color:rgb(10,100,102);">Regmeet</b> facilita una herramienta de fácil uso mediante la cual todas aquellas reuniones de conocimiento y de difusión pública, podrán ser expuestas a todo el público de una manera fácil y cómoda, a través de la web. </p>

                <p>Todo el público podrá escuchar la reunión y saber con exactitud quienes fueron las personas involucradas en dicha reunión, así como la participación de cada una de ellas. Además podrán ver documentos relacionados y una descripción de la misma, de forma tal que se involucren dentro del tema tratado. </p>
                
                <?php echo Html::img("regmeet/confianza.jpg","","style='width:230px;float:left;margin-right:17px;'") ?>
                <p style="margin-top:15px;">
                    <b style="font-family:'Century Gothic';font-size:14px;color:rgb(10,100,102);">¿Cómo funciona?</b>
                    <br><br>
                    Ésta aplicación funciona siguiendo una serie de pasos. Inicialmente para grabar la reunión, al terminar ésta podréis tener toda la grabación disponible en internet, accediendo a ella desde vuestra página web corporativa donde podrás configurar las sesiones antes de publicarlas.
                </p>

                <p style="text-align:center;color:grey;font-size:14px;float:left;margin-top:20px;"><b>No esperes más, solicita ya tu aplicación y comienza a disfrutar de las grandes ventajas que te ofrece.</b></p>
            </div>
        </div>
</div>

<div class="capa-contenido" id="contact" style="display:none;">
    <div class="fondo_titulo"><p>Contacto</p></div>
        <div id="contacto">
            <div class="contacto-empresa">
                 <p style="font-size:14px;color:#BF4337;font-weight:bold"><span class="glyphicon glyphicon-earphone"></span> 690 069 872 <i class="glyphicon glyphicon-envelope" style="padding-left:20px;"></i> info@regmeet.com </p> 
                <span> <p>
                No dudes en ponerte en contacto con nosotros para pedir mas información, bien sea por teléfono o email. También puedes usar el siguiente formulario si quieres que nos pongamos en contacto contigo.
                </span></p>
                <div>
                    <!--<iframe style="height:300px;width:250px;padding:5px;float:left;margin-right:30px;" src="http://www.mapquest.com/embed?hk=2-vVM1lWGn" marginwidth="0" marginheight="0" frameborder="0" scrolling="no"></iframe>-->
                    <form class="form-horizontal" style="margin-top:30px;margin-left:25px;width:520px;">
                      <div class="form-group">
                        <b style="float:left;width:70px;margin-bottom:5px;font-size:11px;margin-left:15px;line-height:25px;">Nombre</b>
                       
                          <input type="text" class="form-control input-sm" placeholder="nombre" style="width:450px;float:left;margin-bottom:5px;opacity:0.7;color:grey;">
                       
                       
                        <b style="float:left;width:70px;margin-bottom:5px;font-size:11px;margin-left:15px;line-height:25px;">Teléfono</b>
                      
                          <input type="text" class="form-control input-sm" placeholder="000" style="width:170px;height:25px;float:left;margin-bottom:5px;opacity:0.7;color:grey;">
                       

                        <b style="float:left;width:50px;margin-bottom:5px;font-size:11px;margin-left:15px;line-height:25px;">Email</b>
                        
                          <input type="email" class="form-control input-sm" placeholder="@" style="width:215px;margin-bottom:5px;opacity:0.7;color:grey;">
                       
                        <b style="float:left;width:70px;margin-bottom:5px;font-size:11px;margin-left:15px;line-height:25px;">Asunto</b>
                       
                          <input type="text" class="form-control input-sm" placeholder="asunto" style="width:450px;float:left;margin-bottom:5px;opacity:0.7;color:grey;">
       
                        <b style="float:left;width:70px;margin-bottom:5px;font-size:11px;margin-left:15px;line-height:25px;">Mensaje</b>
                        
                        <textarea class="form-control input-sm" rows="7" style="width:450px;opacity:0.7;color:grey;" placeholder=""></textarea>
   
                              <button type="submit" class="btn btn-default" style="background:#333;color:#fff;height:25px;font-size:10px;float:right;margin-right:15px;margin-bottom:3px;margin-top:10px;line-height:10px;" disabled=disabled>ENVIAR</button>
                          </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>