<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>Steff</title>
  <?php Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css('estilos') ?>
  <?php Tag::css('bootstrap/css/bootstrap.min') ?>
  <link rel="shortcut icon" href="" />
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js("scripts/jquery.min") ?>
  <?php echo Tag::js("datatable/jquery") ?>
  <?php echo Tag::js("datatable/jquery.dataTables.min") ?>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".datatable").DataTable({
      "language":{
        "sProcessing":     "Procesando...",
        "sLengthMenu":     "Mostrar _MENU_ registros",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst":    "Primero",
            "sLast":     "Último",
            "sNext":     "Siguiente",
            "sPrevious": "Anterior"
        },
        "oAria": {
            "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
    }
    });
    })
  </script>
</head>
 <body style="background:#fff;">

        <?php echo View::content(); ?>

      <?php echo View::partial("entidad/footer") ?>
    
 </body>
</html>

