    <section class="banner">
      <section class="app-img">
        <?php echo Html::img("regmeet/app_banner_new1.png","","class='app_img'") ?>
        <!--<p>Una herramienta enfocada principalmente en la difusión de reuniones de interés público de forma sencilla</p>-->
        <?php //echo Html::img("regmeet/micro.png","","class='microfono'") ?>
        <div class="botones">
          <p><div class="boton-a">1</div> Crear Sesiones</p>
        </div>
        <div class="botones-b">
          <p><div class="boton-b">2</div> Añadir participantes</p>
        </div>
         <div class="botones-c">
          <p><div class="boton-c">3</div> Grabar participación</p>
        </div>
        <div class="botones-d">
          <p><div class="boton-d">4</div> Guardar sesión</p>
        </div>
         <div class="botones-e">
          <p><div class="boton-e">5</div> Configurar sesión</p>
        </div>
        <div class="botones-f">
          <p><div class="boton-f">6</div> Publicar sesión</p>
        </div>
  
      </section>
      <section class="slyder">      
        <div class="icono-logo">
          <?php echo Html::img("regmeet/icono.png") ?>
        </div>
        <?php //echo Html::img("regmeet/reunion.png") ?>
       <ul class="btn-banner">
          <li style="background:#333;"></li>
          <li style="background:#BF4337;"></li>
          <li style="background:#333;"></li>
          <li style="background:#BF4337;"></li>
        </ul>
        <div class="fluid_container">
    
        <div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
          <?php echo Html::img("images/") ?>
            <div data-thumb="http://regmeet.hol.es/img/images/slides/thumbs/reunion.png" data-src="http://regmeet.hol.es/img/images/slides/reunion.png">
                <div class="camera_caption fadeFromBottom">
                   Regmeet te ofrece una herramienta de calidad
                </div>
            </div>
            <div data-thumb="http://regmeet.hol.es/img/images/slides/thumbs/empresas.jpg" data-src="http://regmeet.hol.es/img/images/slides/empresas.jpg">
                <div class="camera_caption fadeFromBottom">
                   Facilita la difusión de tus reuniones 
                </div>
            </div>
            <div data-thumb="http://regmeet.hol.es/img/images/slides/thumbs/reunion2.jpg" data-src="http://regmeet.hol.es/img/images/slides/reunion2.jpg">
                <div class="camera_caption fadeFromBottom">
                   Te permite grabar y visualizar automaticamente en la web
                </div>
            </div>
            <div data-thumb="http://regmeet.hol.es/img/images/slides/thumbs/empresas_junta.jpg" data-src="http://regmeet.hol.es/img/images/slides/empresas_junta.jpg">
                <div class="camera_caption fadeFromBottom">
                   Tu propia web corporativa 
                </div>
            </div>
            <div data-thumb="http://regmeet.hol.es/img/images/slides/thumbs/reuniones.jpg" data-src="http://regmeet.hol.es/img/images/slides/reuniones.jpg">
       
            </div>
            <div data-thumb="http://regmeet.hol.es/img/images/slides/thumbs/reuniones_empresa.jpg" data-src="http://regmeet.hol.es/img/images/slides/reuniones_empresa.jpg">
                <div class="camera_caption fadeFromBottom">
                    Donde podrás personalizar tu reunión para posteriormente publicarla
                </div>
            </div>
        </div>
   
    </div>
    
      </section>
    </section>
    <section class="mensaje-empresa">
        <h2>Una <span style="font-family:Impact;color:#E40E26;">herramienta enfocada</span> principalmente en la difusión <br>de reuniones de interés público de forma sencilla <!--<span class="link-solicitud">Solicitar</span>--><br>
        </h2>

    </section>