<section class="menu-right">
	<div class="fondo_titulo"><p>Sesiones Recientes</p></div>
	<div class="sesiones_recientes" style="padding-left: 10px;padding-right:10px;padding-top:5px;">
		<ul>
			<li>
				<?php echo Html::img("regmeet/logo_empresa1.jpg","","style='width:50px;height:50px;'") ?>
				<div class="titulo-sesion"><b>Starbucks Coffee - <span>Conferencia de Importación 2015</span> <br><small style="float:right">16-01-2015</small></b><div class="link-escuchar"><?php //echo Html::img("regmeet/microfono.png","","style='width:20px;height:20px;border:0px;'") ?></div></div><br>
				<div class="texto-sesion">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus consequatur earum molestiae tatibus consequatur earum molestiae. </div>
			</li>
			<li style="padding-top:5px;">
				<?php echo Html::img("regmeet/logo_empresa2.jpg","","style='width:50px;height:50px;'") ?>
				<div class="titulo-sesion"><b>Dell - <span>Sesion II Nuevas Tecnologías</span> <br><small style="float:right">16-01-2015</small></b><div class="link-escuchar"><?php //echo Html::img("regmeet/microfono.png","","style='width:20px;height:20px;border:0px;'") ?></div></div><br>
				<div class="texto-sesion">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus consequatur earum molestiae tatibus consequatur earum molestiae.</div>
			</li>
			<li style="padding-top:5px;">
				<?php echo Html::img("regmeet/logo_empresa1.jpg","","style='width:50px;height:50px;'") ?>
				<div class="titulo-sesion"><b>Starbucks Coffee - <span>Conferencia de Importación 2015</span> <br><small style="float:right">16-01-2015</small></b><div class="link-escuchar"><?php //echo Html::img("regmeet/microfono.png","","style='width:20px;height:20px;border:0px;'") ?></div></div><br>
				<div class="texto-sesion">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus consequatur earum molestiae tatibus consequatur earum molestiae. </div>
			</li>
			<li style="padding-top:5px;">
				<?php echo Html::img("regmeet/logo_empresa2.jpg","","style='width:50px;height:50px;'") ?>
				<div class="titulo-sesion"><b>Dell - <span>Sesion II Nuevas Tecnologías</span> <br><small style="float:right">16-01-2015</small></b><div class="link-escuchar"><?php //echo Html::img("regmeet/microfono.png","","style='width:20px;height:20px;border:0px;'") ?></div></div><br>
				<div class="texto-sesion">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus consequatur earum molestiae tatibus consequatur earum molestiae.</div>
			</li>
		</ul>
	</div>
</section>